[project]
name = "ricette"
version = "0.1.0"
description = "Le Ricette di Daniela e Mirko"
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["zensical==0.0.9"]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = []
