[project]
site_name = "Le Ricette di Daniela e Mirko"
site_url = "https://maischberger.it/"
repo_url = "https://github.com/baol/recipes"
copyright = "Copyright ©️ 2025 Daniela & Mirko Maischberger"


[[project.exclude_docs]]
pattern = ".obsidian"

[[project.exclude_docs]]
pattern = ".trash"

[[project.exclude_docs]]
pattern = "Templates"

[[project.exclude_docs]]
pattern = "*.base"

[project.plugins.search]
[project.plugins.tags]

[project.theme]
name = "material"
favicon = "images/100allora.png"
custom_dir = "overrides"
language = "it"
logo = "images/100allora.png"
features = ["search.suggest"]

[project.theme.palette]
scheme = "slate"
primary = "white"
accent = "yellow"

[project.theme.font]
text = "Noto"

[project.extra.consent]
title = "Usiamo i cookie!"
description = "Utilizziamo i cookie per riconoscere le tue visite ripetute e le tue preferenze, nonché per misurare l'efficacia della nostra documentazione e se gli utenti trovano ciò che stanno cercando. Con il tuo consenso, ci aiuti a migliorare la nostra documentazione."

[project.extra.analytics]
provider = "google"
property = "G-X3S66S3427"

[project.extra.analytics.feedback]
title = "Questa pagina è stata utile?"

[[project.extra.analytics.feedback.ratings]]
icon = "material/emoticon-sad-outline"
name = "Questa pagina potrebbe essere migliorata"
data = 0
note = "Grazie per il tuo feedback! Aiutaci a migliorare questa pagina utilizzando il nostro <a href=\"https://github.com/baol/recipes/issues/new/?title=[Feedback]+{title}+-+{url}\" target=\"_blank\" rel=\"noopener\">modulo di feedback</a>."

[[project.extra.analytics.feedback.ratings]]
icon = "material/emoticon-happy-outline"
name = "Questa pagina è stata utile"
data = 1
note = "Grazie per il tuo feedback!"
